### ISSUE TITLE
type problem

### ISSUE THREAD

**Issue by DavideFasolo** [DavideFasolo/HTG#9]
problem in file "out_dxf.py":
from line 38 to 42, the "foro#" definition from class "Forotag" causes an error (str instead of real). Still finding a cause/solution:
`        exec('foro%d = Forotag(%f,%f,%f,%f,%f,%f,%d,4,%s,"%s",%s,"%s","%s",%s)' % (i,cx,cy,cz,cr,
                                                                                      cf.htesto,cf.angolo,i,
                                                                                      cf.cer_colore,cf.cer_livello,
                                                                                      cf.etk_colore,cf.etk_livello,
                                                                                      cf.tes_livello,cf.tes_colore))`
Maybe it needs some type definition/conversion in class definition from "KG_dxf.py", but i'm a little sick these days, so coding is difficult as sleeping 🤒

**Comment by giuliocaccin** [comment]
I added a stand alone unit test to point out some inconsistencies but I did not understand the purpose of the code. Please check unit test purpose because it's a really a really useful tool to quickly check how to proceed in situations like this without starting up the application.

**Comment by DavideFasolo** [comment]
The code itself it's a starting point to future upgrades to the Forotag class, for graphics and other outputs, and finally a realtime editing of every hole.
